<?php
/**
 * Northrop & Johnson Theme Functions
 *
 * Generated by Plug & Press
 *
 * @package northrop-johnson
 */

// ═══════════════════════════════════════════════════════════════════════════
// FONTS
// Fonts are bundled locally in theme.json - no external CDN required.
// ═══════════════════════════════════════════════════════════════════════════

defined('ABSPATH') || exit;

// ═══════════════════════════════════════════════════════════════════════════
// THEME ASSETS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Enqueue theme assets - FRONTEND ONLY
 */
function northrop_johnson_enqueue_assets() {
    // Theme stylesheet (minimal CSS - all styling via theme.json)
    wp_enqueue_style(
        'northrop-johnson-style',
        get_stylesheet_uri(),
        array(),
        wp_get_theme()->get('Version')
    );

    // GSAP for animations
    wp_enqueue_script('gsap', 'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js', array(), '3.12.5', true);
    wp_enqueue_script('gsap-scroll-trigger', 'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js', array('gsap'), '3.12.5', true);

    // Theme animations
    wp_enqueue_script(
        'northrop-johnson-animations',
        get_template_directory_uri() . '/assets/js/animations.js',
        array('gsap', 'gsap-scroll-trigger'),
        '1.0.0',
        true
    );
}
add_action('wp_enqueue_scripts', 'northrop_johnson_enqueue_assets');

// ═══════════════════════════════════════════════════════════════════════════
// THEME SETUP
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Theme setup - add theme support
 */
function northrop_johnson_setup() {
    // Add support for block styles
    add_theme_support('wp-block-styles');

    // Add support for editor styles
    add_theme_support('editor-styles');

    // Enqueue editor styles
    add_editor_style('style.css');

    // Add support for responsive embeds
    add_theme_support('responsive-embeds');

    // Add support for wide alignments
    add_theme_support('align-wide');
}
add_action('after_setup_theme', 'northrop_johnson_setup');

/**
 * Register Pattern Categories
 * Main "Plug & Press" category groups all site patterns for easy discovery
 */
function northrop_johnson_pattern_categories() {
    // Main Plug & Press category - appears first in pattern library
    register_block_pattern_category( 'plug-and-press', array(
        'label' => __( 'Plug & Press', 'northrop-johnson' ),
    ) );

    // Theme-specific category
    register_block_pattern_category( 'northrop-johnson', array(
        'label' => __( 'Northrop & Johnson', 'northrop-johnson' ),
    ) );
}
add_action( 'init', 'northrop_johnson_pattern_categories' );

// ═══════════════════════════════════════════════════════════════════════════
// MEDIA LIBRARY IMPORT
// Import theme images into WordPress Media Library on theme activation
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Import theme images to Media Library on theme activation
 */
function northrop_johnson_import_theme_media() {
    // Check if already imported
    if (get_option('northrop_johnson_media_imported')) {
        return;
    }

    $images_dir = get_template_directory() . '/assets/images';

    if (!is_dir($images_dir)) {
        return;
    }

    // Get all image files
    $allowed_types = array('jpg', 'jpeg', 'png', 'gif', 'webp', 'svg');
    $files = scandir($images_dir);
    $imported_count = 0;

    foreach ($files as $file) {
        if ($file === '.' || $file === '..') {
            continue;
        }

        $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
        if (!in_array($ext, $allowed_types)) {
            continue;
        }

        $file_path = $images_dir . '/' . $file;

        // Check if this image already exists in media library
        $existing = get_posts(array(
            'post_type' => 'attachment',
            'meta_query' => array(
                array(
                    'key' => '_northrop_johnson_theme_image',
                    'value' => $file,
                )
            ),
            'posts_per_page' => 1,
        ));

        if (!empty($existing)) {
            continue;
        }

        // Get file info
        $filetype = wp_check_filetype($file, null);
        $title = pathinfo($file, PATHINFO_FILENAME);
        $title = ucwords(str_replace(array('-', '_'), ' ', $title));

        // Copy file to uploads directory
        $upload_dir = wp_upload_dir();
        $new_file = $upload_dir['path'] . '/' . $file;

        if (!copy($file_path, $new_file)) {
            continue;
        }

        // Create attachment
        $attachment = array(
            'guid' => $upload_dir['url'] . '/' . $file,
            'post_mime_type' => $filetype['type'],
            'post_title' => $title,
            'post_content' => '',
            'post_status' => 'inherit'
        );

        $attach_id = wp_insert_attachment($attachment, $new_file);

        if (!is_wp_error($attach_id)) {
            // Generate attachment metadata
            require_once(ABSPATH . 'wp-admin/includes/image.php');
            $attach_data = wp_generate_attachment_metadata($attach_id, $new_file);
            wp_update_attachment_metadata($attach_id, $attach_data);

            // Mark as theme image for tracking
            update_post_meta($attach_id, '_northrop_johnson_theme_image', $file);

            $imported_count++;
        }
    }

    // Mark as imported
    update_option('northrop_johnson_media_imported', true);

    if ($imported_count > 0) {
        // Add admin notice
        set_transient('northrop_johnson_media_notice', $imported_count, 30);
    }
}
add_action('after_switch_theme', 'northrop_johnson_import_theme_media');
// Also run on admin_init for Playground preview where theme is already active
add_action('admin_init', 'northrop_johnson_import_theme_media');

/**
 * Show admin notice after media import
 */
function northrop_johnson_media_import_notice() {
    $count = get_transient('northrop_johnson_media_notice');
    if ($count) {
        delete_transient('northrop_johnson_media_notice');
        echo '<div class="notice notice-success is-dismissible">';
        echo '<p><strong>Northrop & Johnson:</strong> ' . sprintf(__('%d theme images have been imported to your Media Library.', 'northrop-johnson'), $count) . '</p>';
        echo '</div>';
    }
}
add_action('admin_notices', 'northrop_johnson_media_import_notice');
